### ISSUE TITLE
It is not a real error when links to github don't exist, for files not on master

### ISSUE THREAD

**Issue by jessitron** [atomist/docs-sdm#15]
like, when you create a new file on a branch, the branch build fails because the generated github link doesn't work because it's looking for it on master. We should make these non-errors

**Comment by gjtorikian** [comment]
Argh, this happened again: https://github.com/atomist/docs/pull/284

Just spitballing, but one potential solution is to use html-proofer's [`url_swap` option](https://github.com/gjtorikian/html-proofer/#configuration). We could replace the hardcoded `master` with `$CURRENT_BRANCH_NAME` in [the test script](https://github.com/atomist/docs/blob/817331c9b4ab0f9cb82b422e95aee22edf144543/htmlproof.sh#L26). For example:

```
CURRENT_BRANCH_NAME=git branch | grep \* | cut -d ' ' -f2

htmlproofer --url-swap https://github.com/atomist/docs/edit/master/docs, https://github.com/atomist/docs/edit/$CURRENT_BRANCH_NAME/docs
```

Something like this. My bash-fu is rusty, but the test would be checking for the branch name in a PR and `master` on...master.

What do you think?

**Comment by jessitron** [comment]
that sounds totally cromulent

except we don't use htmlproofer anymore, we use htmltest https://github.com/wjdp/htmltest ... it doesn't seem to have that option. 
I'm gonna look at mkdocs options, to see if we can change the link when we build the branch version of the site

**Comment by gjtorikian** [comment]
Hmm, then I guess the docs for these are wrong? https://github.com/atomist/docs/blob/71c5f6e21760bc5a5635634510b06a6faa9218b5/README.md#htmlproofer

I guess what it means is, locally, you can use html-proofer, but on a PR, htmltest is used via the SDM?
